services:
  wvnr:
    build:
      context: .
    image: wvnr_img
    container_name: wvnr_img
    volumes:
      - /path/to/your/netflow:/opt/netflow # Mount netflow data to a volume
    ports:
      - "83:80"
      - "2055:2055/udp"
    restart: unless-stopped
